services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    networks:
      - observe


  prometheus:
    image: prom/prometheus:main-distroless
    ports:
      - 9090:9090 
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observe

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000 
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - observe

networks:
  observe:
    driver: bridge
