services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    networks:
      - observe


  prometheus:
    image: prom/prometheus:main-distroless
    ports:
      - 9090:9090 
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observe


networks:
  observe:
    driver: bridge
